refactor(animation): new animations engine
This commit is comprised of the following interactively rebased commits
from PR #1002 by @thearturca.

1a184a4442d3a3658bf0a1e6f61b0792a0488183
refactor(animation): move animations to its own mod

First step for more rusty version animations. The goal is to make
animations more generic so its easier to add new animations to komorebi!

d3ac6b72c225f830a4e91d2e1197e6dcb5c68430
refactor(animation): reduce mutex calls on `ANIMATION_STYLE`

8a42b738feeb627bbe862f0edbe49158ab809eba
refactor(animation): introduce `Lerp` trait

e449861c10badcc229d137d22c3d4f5e08befd91
refactor(animation): generalized ANIMATION_MANAGER

Instead of a isize key for the ANIMATION_MANAGER HashMap, now we use a
String key. For window move animation, the key would be
`window_move:{hwnd}`.

This allows us to use single manager for more types of animations.

67b2a7a284e7aa367d90c39d22fae199866ae40c
feat(animation): introduce `AnimationPrefix` enum

8290f143a662928274f8fce538a29b57efd26294
feat(animation): introduce `RenderDispatcher` trait

2400d757fec9305c1f0d6b022443f091f123bd7b
feat(animation): implement window transparency animation

This commit also fixes graceful shutdown of animations by disabling them
before exit and wait for all remaining animations for 20 seconds.

44189d8382f63cdd42ef77e7007a4e73dbe369c2
refactor(animation): move generation of `animation key` to `RenderDispatcher`

e502cb3ffb8cee3fbc4ddeca6311b6016abc49d9
refactor(animation): rename `animation` mod to `engine`

Linter was upset about this:
> error: module has the same name as its containing module

369107f5e067e5adf6d82b91551e7384f4f66dcd
feat(config): adds per animation configuration options

Originally static config only allowed global config for animations.

Since this refactor introduces the abilty to add more type of
animations, this change allows us to configure `enabled`, `duration` and
`style` state per animation type.

Now each of them take either the raw value or a JSON object where keys
are the animation types and values are desired config value. Also adds
support for per animation configuration for komorebic commands.